// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKjV60hIe7L9OJuCjknbbnKwQ_ijzqCNg',
    appId: '1:371985841324:web:7451607278dc5f270bb309',
    messagingSenderId: '371985841324',
    projectId: 'tryvel-272b7',
    authDomain: 'tryvel-272b7.firebaseapp.com',
    storageBucket: 'tryvel-272b7.firebasestorage.app',
    measurementId: 'G-C7F8QN3P0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD90hPYy4paGWUX7fk4BLfGOx2dsHeKpX8',
    appId: '1:371985841324:android:aa465e50017be68f0bb309',
    messagingSenderId: '371985841324',
    projectId: 'tryvel-272b7',
    storageBucket: 'tryvel-272b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHmA_5jF_MRHNQ-kf7ZctOsmSn0mdNR8o',
    appId: '1:371985841324:ios:c9fe85c0872537ac0bb309',
    messagingSenderId: '371985841324',
    projectId: 'tryvel-272b7',
    storageBucket: 'tryvel-272b7.firebasestorage.app',
    iosBundleId: 'com.example.tryvel',
  );
}
